### ISSUE TITLE
Boxee Box not showing Genres properly

### ISSUE THREAD

**Issue by difelice** [vidalvanbergen/ViMediaManager#35]
Hi,

First, this is the best media manager for mac I have found.

So far I'm having minor issues with the *Boxee Box*, I know you don't have a way to test this device so I hope I can help.

### Genres
Looks like Boxee Box supports a specific list of genres:

> The genres tag can include only the supported descriptors, they should be separated be space and comma. “,”.
> Genre List: ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY, FANTASY, FILM_NOIR, HISTORY, MUSIC, MUSICAL, MYSTERY, NEWS, ROMANCE, SCI_FI, SHORT, SPORT, THRILLER, WAR, WESTERN

**Source**: http://boxee.zendesk.com/entries/510215-creating-an-nfo-file

Not sure how can we deal with this, could be mapping genres? Ex.:

`
{
  "SCI_FI" : ["SCIENCE-FICTION", "SCIENCE FICTION"],
}
`
### Trailers
On the movie info view there's no *trailers*, not sure how this is implemented on Boxee Box though.

Thanks.

**Comment by vidalvanbergen** [comment]
Is Science fiction the only problem? or are there more?

In the latest nightly build, i've made ViMM change 'Science-Fiction' and 'Science Fiction' to 'SCI_FI', and any spaces translated to "_" on NFO file save.
https://www.mediafire.com/?8j6ve2f4je6et

**Comment by difelice** [comment]
Thanks! 

Genres seems to work now, some of them are not in the list though: ANIMATION, ROMANCE

The issue with trailers is the *Youtube URL*, if I replace the first <trailer> occurrence with a **mp4 URL** it works. Is it possible to change the trailer source?

Thank you.

**Comment by difelice** [comment]
Genres seems to work fine in nightly version. Thanks.
