### ISSUE TITLE
Crashes Constantly

### ISSUE THREAD

**Issue by hanej** [vidalvanbergen/ViMediaManager#37]
I've been using this amazing piece of software for years and never had a problem.  I don't know if it's  a Sierra compatibility issue or something else but I can barely use this application anymore.  It crashes all the time.  For example, if I go to the edit screen and click on the Next button, it hangs forever.

**Comment by vidalvanbergen** [comment]
Have you tried a complete reset? (Instructions: http://forum.kodi.tv/showthread.php?tid=109976&pid=1542973#pid1542973 )

ViMM may be getting stuck if you're using a network attached drive with slow network speed
