### ISSUE TITLE
The details on the two different DMG release files is not documented.

### ISSUE THREAD

**Issue by peterclauterbach** [vidalvanbergen/ViMediaManager#38]
I am looking to try out ViMediaManager on my mac. I want to use the released DMG files, since they are easier to install and run than the .zip files.

Under the [Releases](https://github.com/vidalvanbergen/ViMediaManager/releases) link on GitHub for ViMediaManager, there are two different DMG files:

[ViMediaManager v7a14](https://github.com/vidalvanbergen/ViMediaManager/releases/tag/v7a14)

1. vimediamanager_v0.7a14c.dmg
1. vimediamanager_v0.7a14i.dmg

- What is the different between the 'c' version and the 'i' version?
- Are they for different platforms, or OS X releases.
- Do I need one of them or both?

I looked all over the GitHub site, and in the user doc, but could not find this detail.

Expectation:
The different DMG files in the release are documented at the point of download with instructions about which one you need.

**Comment by vidalvanbergen** [comment]
Thank you for your interest in ViMediaManager!

I'm sorry for the confusion, the 'i' version stands for 'intel', it's the more stable version overall, but doesn't support Retina screens, basically use this if you're on an older OS version.
The 'c' version stands for Cocoa, which is slightly faster, and does support Retina screens.

You'll only need to download one of those versions.

**Comment by peterclauterbach** [comment]
Thanks, and I see you already updated the download page. Closing this issue.
