### ISSUE TITLE
VI Media Manager not working after having upgraded to OSX 10.13.4

### ISSUE THREAD

**Issue by TaT-DK** [vidalvanbergen/ViMediaManager#41]
Love the tool and is very sad that it does not work after upgrading to 
OSX 10.13.4

Will you fix or ?

**Comment by vidalvanbergen** [comment]
ViMediaManager doesn't show any issues on 10.13.4 for me, try downloading the latest release from here:
https://github.com/vidalvanbergen/ViMediaManager/releases

or resetting ViMM by removing it's preferences and settings like so:

Remove these files and folders:
/Users/YOURNAME/Library/Application Support/ViMediaManager/
/Users/YOURNAME/Library/Preferences/com.vidalvanbergen.vimediamanager-alpha.plist
/Users/YOURNAME/Library/Saved Application State/com.vidalvanbergen.vimediamanager-alpha.savedState/
/Users/YOURNAME/Library/Caches/com.vidalvanbergen.vimediamanager-alpha/

Do a search with the terminal:
sudo find / -name *vidalvanbergen*
or
sudo find / -name *vimediamanager*

And remove the item in the following location: (The numbers may differ)
/private/var/db/BootCaches/6D4C0300-582B-4CC1-A86E-D1F13EF7BC07/app.com.vidalvanbergen.vimediamanager-alpha.playlist

When all traces of ViMediaManager's previous install have been removed, reboot your computer and re-instal ViMediaManager, you can use the link below to download the latest nightly build:
