### ISSUE TITLE
NilObjectException

### ISSUE THREAD

**Issue by LTLNEMO** [vidalvanbergen/ViMediaManager#42]
I keep getting this error and the app shuts down.  The only thing that has changed was that I added <set> tags to .nfo files.  I have also done a complete reset of the app following your instructions 

![screen shot 2018-04-24 at 11 09 30 pm](https://user-images.githubusercontent.com/21018413/39224306-b3d2c7c0-4814-11e8-8be9-3bb10dcf3a9d.png)

**Comment by vidalvanbergen** [comment]
What were you doing just before the error popped up?

**Comment by LTLNEMO** [comment]
Updating List (movies)

**Comment by vidalvanbergen** [comment]
Do you know which movie it gives the error on? if so can you send the .nfo file of it?

**Comment by LTLNEMO** [comment]
I have no idea which movie it gives the error on because it doesn't necessarily go in order.  I might just delete all the .nfo files I have and start over

**Comment by LTLNEMO** [comment]
I'm currently going through each .nfo file to see which one was giving VMM the error.  However, one thing that I noticed is that updating the metadata overwrites my <set> tags.  Is there a way to not overwrite info that doesn't follow the .nfo formatting rules of VMM

**Comment by LTLNEMO** [comment]
I did use Update Metadata but when I do it rewrites and removes <set> through </set>

I couldn't find the culprit last night.  I'm gonna try again today. 

My media is on a Synology NAS

**Comment by vidalvanbergen** [comment]
That might be the cause then, it seems that ViMM has a problem doing a batch download of information to network attached storage devices.

If there's a way for you to connect directly to the device you might be able to get it working correctly.
