### ISSUE TITLE
Actors not being downloaded

### ISSUE THREAD

**Issue by JustinAiken** [vidalvanbergen/ViMediaManager#43]
**Version:** 0.7a15c (not using a16, since the non-cocoa version is near unusable on a rMBP)

- Up until recently, was downloading the cast just fine..
- Now isn't getting any of the cast

Tried on multiple movies

**Comment by vidalvanbergen** [comment]
Is it just the thumbnail images or also the names of the cast that isn't being downloaded?

I believe that an update of OS X caused images in a15 and below not to download at all, which I managed to fix through a workaround in a16, with the unfortunate side-effect that it seemed to crash the Cocoa version.

**Comment by JustinAiken** [comment]
> Is it just the thumbnail images or also the names of the cast that isn't being downloaded?

Neither.. the director/writers' names get scraped, but the rest of the cast is blank

**Comment by vidalvanbergen** [comment]
Apparantly IMDb has moved to secure (https) pages which ViMM was unable to scrape, I've fixed it in the new release.
I'll attach a Cocoa version to this thread, let me know how it works.
[ViMediaManager_v0.7.17.180426_Cocoa.zip](https://github.com/vidalvanbergen/ViMediaManager/files/1953051/ViMediaManager_v0.7.17.180426_Cocoa.zip)

**Comment by JustinAiken** [comment]
Sweet! Tried 0.7.17c.dmg from the releases page (clicked it before seeing this thread), and I'm getting actors including images 👍

**Comment by vidalvanbergen** [comment]
Glad to hear this seems to be working again. ;)
