### ISSUE TITLE
Resolution icon says "1080p" even if the title is 2160 aka 4k

### ISSUE THREAD

**Issue by surrounded** [vidalvanbergen/ViMediaManager#44]
Title Resolution Icon seems to be limited to 1080p because titles with a resolution of 2160 aka 4k still have a "1080p" resolution icon.

**Comment by vidalvanbergen** [comment]
Thanks for letting me know, I've included a debug version for you to try out, you may need to refresh the list before the new resolutions show up.

Let me know if it works.
[ViMediaManager_v0.7.17.180519_Cocoa.zip](https://github.com/vidalvanbergen/ViMediaManager/files/2019789/ViMediaManager_v0.7.17.180519_Cocoa.zip)
