### ISSUE TITLE
version  number confusion

### ISSUE THREAD

**Issue by core-code** [vidalvanbergen/ViMediaManager#45]
the newest release is referred to as
v0.7a17 (download title)
v0.7.17c (download filename #1)
v0.7.17i (download filename #2)
0.7.0.1.17 (bundle version)
v0.7α17 (short version string)

so which is it? i am confused, and 3rd party updater apps will have a hard time keeping vimediamanager up-to-date unless a sane version number system is used in a consistent way.

in addition to the confusion mentioned above, some releases just have version number mistakes in them, e.g.:
v0.7α16 had the bundle version "0.7.0.1.24" which makes it, to macOS, the newest version released to date.

**Comment by vidalvanbergen** [comment]
My apologies, the latest version is just v0.7a20. (0.7.0.1.20 Due to how Xojo builds version numbers.) No more intel/cocoa separate builds.
