### ISSUE TITLE
ViMediaManager

### ISSUE THREAD

**Issue by TaT-DK** [vidalvanbergen/ViMediaManager#46]

**Comment by TaT-DK** [comment]
Hi, 

My ViMediaManager freezes up and stops working when it tries to download Logo Images.
Also it doesn not show poster art in the List anymore.

Generally it has slowed down and is very unstable and <i do not know why.

I am on Mac OSX 10.14.2 and 07.a.18i

I have tried to delete all the files you and reinstall, you once gave me a list of files and folders to try and delete, but that did not work

Any idea ?

**Comment by vidalvanbergen** [comment]
To make sure posters in the list are working, make sure that under Preferences > extras, the option 'Show poster images in media list' is turned on and then 'reload' the list. Sometimes on start-up of the app it may take a little while for ViMM to load all the images.

As for the other problem, I believe it may be an issue on fanart.tv's side which may resolve itself in time. I noticed that issue as well before today, but while trying it again just now it seems to work again.

**Comment by JustinAiken** [comment]
> I noticed that issue as well before today, but while trying it again just now it seems to work again.

Same! Was crashing a week or two ago when downloading fanarts, but working the last few days

**Comment by JustinAiken** [comment]
Seeing crashes again when downloading fanart or posters on 0.7a18c 

Here's what I see in `Console.app`:

![screen shot 2018-12-16 at 4 44 53 pm](https://user-images.githubusercontent.com/1568662/50060494-156e3180-0152-11e9-84da-944ad2774be3.png)
