### ISSUE TITLE
Unable to fetch metadata

### ISSUE THREAD

**Issue by chasetb** [vidalvanbergen/ViMediaManager#47]
Whenever I try to "Fetch Metadata" on any movie or TV show, I immediately get a message stating that the movie or show could not be found. When I limit the amount of words in the search box the result is the same. It does not appear that the application is making queries anymore. I have tried this with the latest release and older releases on my current computer (Mac Pro running macOS 10.14.1) and a VM (Parallels running 10.13.6).

Perhaps the API used to look for metadata is refusing the app's connection?

**Comment by vidalvanbergen** [comment]
Movies should still be functional, let me know if this is indeed an issue.

As for TV Shows, the TVDB has recently updated its API, seemingly finally removing support for v1 which ViMM relied on. I've begun working on updating ViMM to use the latest version which uses a different method of connecting and a different format for their information.

**Comment by vidalvanbergen** [comment]
Should be fixed in the new update.
