### ISSUE TITLE
Some IMDB poster art is not downloading

### ISSUE THREAD

**Issue by enduser001** [vidalvanbergen/ViMediaManager#50]
This is great for helping with pulling IMDB info for music videos, adding that extra bit to the experience. Thank you.

I do have one issue that I hope may be quickly addressed.

I am running into an issue where poster art is not downloading, specifically for music videos or shorts.
1. If a manual search for metadata is used and a result is found with poster art.
2. It does not download the art, but creates an empty poster art file.
3. This empty poster art file is referenced in the nfo file.
4. The path the poster file (if downloaded) is relative and not absolute. I do not know if this is intentional.

I don't know if I need to change a setting or if there is a unique circumstance for the particular media (shorts and music videos) I am using. Your assistance is appreciated.

Thank you.
-End

**Comment by vidalvanbergen** [comment]
Hi End,

I'm not sure whether it'll help, but could you try downloading the last nightly build and let me know if the error is still occurring? Or let me know if you already have it.

[https://www.mediafire.com/file/ompn3s581a6re0b/ViMediaManager.zip/file](https://www.mediafire.com/file/ompn3s581a6re0b/ViMediaManager.zip/file)

With kind regards,
Vidal van Bergen.

**Comment by enduser001** [comment]
Thank you for the prompt reply. I appreciate the quick response.
The issue appears on the nightly and the dmg download here.

**Comment by vidalvanbergen** [comment]
Thank you for the feedback. Could you tell me some of the names of the media this is happening to?

**Comment by enduser001** [comment]
Yes. I am currently cataloging. :-)

Manual search the following:
- Police Message in a Bottle, The (1979) 
- Police Every Little Thing She Does Is Magic, The (1981)
- Police Wrapped Around Your Finger, The (1983)

The Poster art shows in the search results, but doesn't download. Instead an empty jpeg file is created.

**Comment by vidalvanbergen** [comment]
I've uploaded an [experimental build](https://www.mediafire.com/file/5jqormoh739d7nm/ViMediaManager-universal.zip/file) that should have a fix for the error, and is also the first 'universal' build for the new M1 Macs.

Let me know if it works correctly

[https://www.mediafire.com/file/5jqormoh739d7nm/ViMediaManager-universal.zip/file](https://www.mediafire.com/file/5jqormoh739d7nm/ViMediaManager-universal.zip/file)

**Comment by enduser001** [comment]
@vidalvanbergen Sweetness dot com! Thank you. You are are both a scholar and a gentleman.
