### ISSUE TITLE
Request: web sources

### ISSUE THREAD

**Issue by JustinAiken** [vidalvanbergen/ViMediaManager#51]
![Screen Shot 2022-04-05 at 9 25 04 AM](https://user-images.githubusercontent.com/1568662/161789230-687d63ce-7235-4838-b0d6-381824940d81.png)

Been getting more webdl's than bluray rips lately

**Comment by vidalvanbergen** [comment]
Good call, here have a minor update:
https://www.mediafire.com/file/awk1lvsk10j01f3/ViMediaManager-TMDBv2.zip/file

Let me know if this helps!
